name: check

on:
  schedule:
    - cron: '*/5 * * * *'  # har 5 minute pe auto
  workflow_dispatch:       # manual button ke liye

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install requests
        run: pip install requests
        
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python Gvc-24-7-Bot.py
