name: GVC Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Har 5 minute pe chalega
  workflow_dispatch:  # Manual run ke liye

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run python Gvc-24-7-Bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python Gvc-24-7-Bot.py
